<a href="https://colab.research.google.com/github/curoled345/Markdown/blob/main/0702_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Numpy 임포트 코드

In [3]:
import numpy as np

- NumPy 배열 만들기
Python의 리스트를 기반으로 배열 생성

In [4]:
# Python의 리스트를 기반으로 배열 생성
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2], [3, 4]])

print("1차원 배열:", arr1)
print("2차원 배열:\n", arr2)

1차원 배열: [1 2 3 4]
2차원 배열:
 [[1 2]
 [3 4]]


In [5]:
# 배열의 차원 (ndim)
print("arr1 차원:", arr1.ndim)
print("arr2 차원:", arr2.ndim)

# 배열의 구조
print("arr2 shape:", arr2.shape)

arr1 차원: 1
arr2 차원: 2
arr2 shape: (2, 2)


- 배열 인덱싱 & 슬라이싱

In [7]:
print("arr1 첫 번째 원소:", arr1[0])
print("arr2 두 번째 행 첫 번째 원소:", arr2[1, 0])

# 슬라이싱
print("arr1 슬라이싱 [1:3]:", arr1[1:3])

arr1 첫 번째 원소: 1
arr2 두 번째 행 첫 번째 원소: 3
arr1 슬라이싱 [1:3]: [2 3]


- 배열 연산 (벡터화)

In [8]:
# 배열에 연산을 일괄 적용하는 벡터화 지원
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("a + b:", a + b)
print("a * 2:", a * 2)
print("a ** 2 (제곱):", a ** 2)

a + b: [11 22 33]
a * 2: [20 40 60]
a ** 2 (제곱): [100 400 900]


- 배열 함수 (sum, mean, max 등)

In [9]:
print("합계:", np.sum(a))
print("평균:", np.mean(a))
print("최댓값:", np.max(a))

합계: 60
평균: 20.0
최댓값: 30


- 배열 생성 함수

In [10]:
zeros = np.zeros((2, 3))  # 0으로 채운 2x3 배열
ones = np.ones((2, 2))    # 1로 채운 2x2 배열
rand = np.random.rand(2, 2)  # 0~1 난수

print("0으로 채운 배열 :\n", zeros)
print("1로 채운 배열 :\n", ones)
print("랜덤 배열 :\n", rand)

0으로 채운 배열:
 [[0. 0. 0.]
 [0. 0. 0.]]
1로 채운 배열:
 [[1. 1.]
 [1. 1.]]
랜덤 배열:
 [[0.02266721 0.10125107]
 [0.23697708 0.48859787]]


- 배열 재구성 (reshape)

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

print("원본 배열 :", arr)
print("재구성한 배열 :\n", reshaped)

원본 배열: [1 2 3 4 5 6]
재구성한 배열:
 [[1 2 3]
 [4 5 6]]


- 배열 병합 및 분할

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 수평 병합
merged = np.concatenate((arr1, arr2))
print("병합된 배열 :", merged)

# 수직 병합
vstacked = np.vstack((arr1, arr2))
print("수직 병합 :\n", vstacked)

병합된 배열: [1 2 3 4 5 6]
수직 병합:
 [[1 2 3]
 [4 5 6]]


- 브로드캐스팅

In [14]:
# 크기가 다른 배열끼리 연산이 자동 적용
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print("브로드캐스팅 결과:\n", matrix + vector)

브로드캐스팅 결과:
 [[11 22 33]
 [14 25 36]]


- 조건 필터링 (Boolean Indexing)

In [15]:
arr = np.array([10, 15, 20, 25, 30])

# 20보다 큰 값만 추출
filtered = arr[arr > 20]
print("20보다 큰 원소:", filtered)

# 조건에 따라 변경도 가능
arr[arr > 20] = 99
print("20보다 큰 원소를 99로 변경:", arr)

20보다 큰 원소: [25 30]
20보다 큰 원소를 99로 변경: [10 15 20 99 99]


11. 난수 관련 함수

In [19]:
# 정수형 (0~9 사이, 5개)
randint_arr = np.random.randint(0, 10, size=5)
print("정수형 배열:", randint_arr)

# 시드 고정 (재현 가능성 보장)
np.random.seed(42)
print("시드 고정된 난수:", np.random.rand(3))

정수형 배열: [4 6 9 2 6]
시드 고정된 난수: [0.37454012 0.95071431 0.73199394]
